# Whatsapp chat analyzer

In [137]:
import pandas as pd 
import re # for regularexpression

In [138]:
f = open("WhatsApp Chat with It Unofficial 2022.txt",'r', encoding='utf-8')  #UTF-8 (Unicode Transformation Format - 8 bit)



#UTF-8 is a character encoding standard that allows computers to store and exchange text in multiple languages and symbols efficiently. It is the most widely used encoding on the web.

In [139]:
data = f.read()

In [140]:
print(data)

5/22/23, 1:52 AM - Messages and calls are end-to-end encrypted. No one outside of this chat, not even WhatsApp, can read or listen to them. Tap to learn more.
5/22/23, 1:55 AM - +91 77248 81647: Happy birthday Nisha 🥳🎉
5/22/23, 1:56 AM - +91 77248 81647: Happy birthday prithviraj 🎉🥳
5/22/23, 2:38 AM - +91 89899 71799: Happiest Birthday to you both 🎉🎉 @919669101981 @917697045869
5/22/23, 5:29 AM - Bhumika IT: Happy birthday Nisha and prithviraj
5/22/23, 7:25 AM - +91 79749 69295: Happy Birthday @919669101981 🎁🎁🎉
5/22/23, 7:34 AM - +91 74896 68532: Happy birthday @919669101981 and @917697045869   🥳🥳
5/22/23, 7:58 AM - +91 96910 98932: Happy Birthday @919669101981🎂🎉🎊
5/22/23, 7:59 AM - +91 96910 98932: @917697045869 Happy Birthday ✨✌️
5/22/23, 8:18 AM - Yuvika Nagle IT: Happy Birthday @919669101981 ✨🥳🥳🥳
5/22/23, 8:47 AM - +91 94075 90087: Happy Birthday @919669101981 @917697045869 🎂✨🥳🥳
5/22/23, 8:49 AM - Pushkal Mishra It: Happy birthday Nisha and Prithviraj 🥳🥳
5/22/23, 8:53 AM - +91 93292 94247: Happy birthday🥳🎂 @919669101981
@917697045869
5/22/23, 10:01 AM - +91 73105 30803: Happy Birthday @919669101981  🥳🥳
5/22/23, 10:03 AM - Kunal IT: Happ birthday Nisha 🥳🥳✨
5/22/23, 10:03 AM - Kunal IT: And Happy birthday prithviraj ✨✨🥳
5/22/23, 10:06 AM - +91 62688 18798: Happy birthday 🥳@917697045869
5/22/23, 10:07 AM - +91 62688 18798: Happy birthday 🥳@919669101981
5/22/23, 10:09 AM - Vivek IT: Happy birthday @917697045869
5/22/23, 10:09 AM - Vivek IT: Happy birthday @919669101981
5/22/23, 10:22 AM - +91 94071 87736: Happy Birthday @919669101981 nd @917697045869 🥳🥳
5/22/23, 10:30 AM - +91 93011 56061: Happy Birthday @919669101981🎉 and @917697045869 🎊
5/22/23, 10:32 AM - Ashutosh IT: Happy birthday nisha  and  prithviraj 🎂🎉🎁
5/22/23, 10:40 AM - +91 91749 93905: Happy birthday @919669101981  and @917697045869 ✨🌈💥
5/22/23, 10:58 AM - +91 93299 05330: Happy birthday @917697045869 🎉🎉
5/22/23, 10:59 AM - +91 93299 05330: Happy birthday @919669101981 🎉🎉
5/22/23, 11:03 AM - Dhurv IT: Happy birthday Prithviraj and Nisha 🥳🥳
5/22/23, 2:43 PM - ~GOURAV IT: Happy Birthday @917697045869 and @919669101981 🎉
5/22/23, 3:02 PM - +91 96178 82239: Happy birthday @917697045869
5/22/23, 3:02 PM - +91 96178 82239: Happy birthday @919669101981
5/22/23, 3:04 PM - +91 79744 92064: Happy birthday @917697045869 and @919669101981 🥳🥳
5/22/23, 5:41 PM - +91 96178 82239: This message was deleted
5/22/23, 6:02 PM - +91 96691 01981: Thank you so much everyone❤️
5/22/23, 7:09 PM - +91 96178 82239: <Media omitted>
5/22/23, 7:09 PM - +91 96178 82239: <Media omitted>
5/22/23, 7:09 PM - +91 96178 82239: <Media omitted>
5/22/23, 7:09 PM - +91 96178 82239: <Media omitted>
5/22/23, 7:39 PM - +91 96178 82239: <Media omitted>
5/22/23, 7:40 PM - +91 79744 92064: This message was deleted
5/22/23, 7:41 PM - Pushkal Mishra It: Kha tho sahi raha ho
5/22/23, 7:41 PM - Pushkal Mishra It: Per option ma he nahi ha
5/22/23, 7:41 PM - +91 96178 82239: Sir ko bheja hai wo 😅
5/22/23, 9:02 PM - Prithviraj Chauhan: Thank you so much everyone for wishes❤️🎂💫🥳
5/23/23, 8:06 AM - +91 96178 82239: Meri proxy laga dena koi
5/23/23, 8:10 AM - Bhumika IT: +1
5/23/23, 12:16 PM - Sheraj IT: Tum kaise lga skti hi..tum to batch A me ho 🙄
5/23/23, 12:16 PM - Arth: Indirectly bol rhi hai meri bhi laga dena
5/23/23, 12:17 PM - Sheraj IT: -1
5/23/23, 12:18 PM - Sheraj IT: Ab tu v batch A me h..
5/23/23, 6:01 PM - +91 93011 56061: 🇮🇳✨
*नमन है हर क्रांतिवीर और उनकी अमर कहानियों को,*
*नहीं भूलेंगे भारत माँ तेरे सपूतों और उनकी क़ुर्बानियों को।*
🇮🇳✨

नमस्कार साथियों !!💫

हिन्दी क्लब एमआईटीएस एवं अखिल भारतीय साहित्य परिषद के संयुक्त तत्वाधान में हमारे स्वतंत्रता संग्राम के क्रांतिवीरों को श्रद्धांजलि अर्पित करने एवं आप सभी को उनके बारे में जागरूक करने के उद्देश्य से *याद करो क़ुर्बानी* कार्यक्रम का आयोजन होने जा रहा है जिसके अंतर्गत 3 प्रतियोगिताओं का आयोजन होना है-

🇮🇳 *'कहानी वीरों की'* जिसके अंतर्गत प्रतिभागी को किसी "ऐसे क्रांतिवीर के बारे में वक्तव्य देना होगा जिनके बारे में हम सभी को कम ज्ञात है या जिन्हें उनके योगदान के अनुरूप पहचान नहीं मिली है"।

🇮🇳 *'क्रांति Quiz'* जिसके अंतर्गत दो चरणों में प्रश्नोत्तरी(पहला चरण लिखित एवं दूसरा चरण मौखिक) "भारतीय स्वतंत्रता संग्राम एवं उसके क्रांतिवीर" इस विषय पर आयोजित की जाएगी।

🇮🇳 *'कला से क्रांति'* जिसके अंतर्गत "स्वतंत्रता संग्राम कालिक दृश्य" या "स्वतंत्रता क्रांतिवीर" इन दो विषयों पर चित्रकला प्रतियोगिता का आयोजन किया जाएगा।

📎विजेताओं को *आकर्षक उपहार एवं प्रमाण पत्र* प्रदान किए जाएंगे साथ ही सभी प्रतिभागियों को *ई प्रमाण पत्र* प्रदान किए जाएंगे।

📎 *पंजीकरण शुल्क--*
एक प्रतियोगिता हेतु - ₹25
दो प्रतियोगिताओं हेतु - ₹40
तीन प्रतियोगिताओं हेतु - ₹60

📌 *दिनाँक - 26 मई 2023 (शुक्रवार)*
📌 *समय - 2 बजे*
📌 *स्थान - कॉन्क्लेव सेन्टर*

🖇️ *फॉर्म लिंक--* https://forms.gle/5f2nJ14vYpmPbbRE8

📌 *जानकारी हेतु संपर्क करें--*
रुद्राक्ष शुक्ला - 8989484091
अथर्व श्रोत्रिय - 8871079163

🖇️ *इंस्टाग्राम--* https://instagram.com/hindiclub.mits?igshid=NTc4MTIwNjQ2YQ==
5/23/23, 6:01 PM - +91 93011 56061: <Media omitted>
5/23/23, 7:19 PM - +91 62634 09068: Good evening everyone,
Please attempt the quiz before 8pm ...
5/24/23, 5:11 AM - +91 96178 82239: _आओ जाने "याद करो कुर्बानी" को_

https://www.instagram.com/p/CsmMm10IgWM/?igshid=MzRlODBiNWFlZA==

LINK - https://forms.gle/5f2nJ14vYpmPbbRE8
5/24/23, 5:11 AM - +91 96178 82239: If anyone interested dm me
5/24/23, 1:57 PM - +91 96178 82239: <Media omitted>
5/24/23, 2:55 PM - +91 96178 82239: Please consider this as the certificate is national level worth 5 credits per competition so if you participate in three it will be 15 points and the winners will be honoured by Jyotriadhitya scindia on 11 June in Shivpuri
5/24/23, 2:56 PM - +91 96178 82239: For more details you can contact me rudraksh Or atharav
5/24/23, 2:57 PM - +91 96178 82239: Itte credit CR ke nhi hote 😅
5/24/23, 4:48 PM - +91 62634 09068: Good evening everyone,
Tomorrow there will be chemistry class from 12pm - 1 pm...
5/24/23, 7:10 PM - +91 62634 09068: <Media omitted>
5/24/23, 7:11 PM - +91 62634 09068: Guys please attempt DSA quizz before 8 ....
5/24/23, 7:11 PM - Arth: Mari Chhori chhoro se kam hai kee 😎
5/24/23, 7:28 PM - +91 93431 43604: null
5/24/23, 7:29 PM - Pushkal Mishra It: <Media omitted>
5/24/23, 7:30 PM - Siddhu Moose Wala: Last 40 saal me dekh lo  rairly 10 me eak do hai kisi kisi year
5/24/23, 7:32 PM - +91 93431 43604: Woi bhai!
Boards aur UPSC jaise ratne ki cheezo me hi charche me rehti h 🤣
5/24/23, 7:37 PM - Arth: Bol na pdhta hai
5/24/23, 7:53 PM - +91 96178 82239: <Media omitted>
5/25/23, 9:41 AM - +91 96178 82239: <Media omitted>
5/25/23, 9:42 AM - +91 96178 82239: guys we will close the form at 8 PM Today so plz register ASAP
5/25/23, 12:19 PM - +91 62634 09068: Guys chemistry class kahan ho rhi hai
5/25/23, 12:19 PM - +91 62634 09068: 🥲🥲🥲
5/25/23, 12:23 PM - +91 62634 09068: Koi toh bta doo😣😣
5/25/23, 12:26 PM - Divyansh Senger IT: 112
5/25/23, 6:40 PM - +91 96178 82239: 🇮🇳✨
*नमन है हर क्रांतिवीर और उनकी अमर कहानियों को,*
*नहीं भूलेंगे भारत माँ तेरे सपूतों और उनकी क़ुर्बानियों को।*
🇮🇳✨

नमस्कार साथियों !!💫

हिन्दी क्लब एमआईटीएस एवं अखिल भारतीय साहित्य परिषद के संयुक्त तत्वाधान में हमारे स्वतंत्रता संग्राम के क्रांतिवीरों को श्रद्धांजलि अर्पित करने एवं आप सभी को उनके बारे में जागरूक करने के उद्देश्य से *याद करो क़ुर्बानी* कार्यक्रम का आयोजन होने जा रहा है जिसके अंतर्गत 3 प्रतियोगिताओं का आयोजन होना है-

🇮🇳 *'कहानी वीरों की'* जिसके अंतर्गत प्रतिभागी को किसी "ऐसे क्रांतिवीर के बारे में वक्तव्य देना होगा जिनके बारे में हम सभी को कम ज्ञात है या जिन्हें उनके योगदान के अनुरूप पहचान नहीं मिली है"।

🇮🇳 *'क्रांति Quiz'* जिसके अंतर्गत दो चरणों में प्रश्नोत्तरी(पहला चरण लिखित एवं दूसरा चरण मौखिक) "भारतीय स्वतंत्रता संग्राम एवं उसके क्रांतिवीर" इस विषय पर आयोजित की जाएगी।

🇮🇳 *'कला से क्रांति'* जिसके अंतर्गत "स्वतंत्रता संग्राम कालिक दृश्य" या "स्वतंत्रता क्रांतिवीर" इन दो विषयों पर चित्रकला प्रतियोगिता का आयोजन किया जाएगा।

📎विजेताओं को *आकर्षक उपहार एवं प्रमाण पत्र* प्रदान किए जाएंगे साथ ही सभी प्रतिभागियों को *ई प्रमाण पत्र* प्रदान किए जाएंगे।

📎 *पंजीकरण शुल्क--*
एक प्रतियोगिता हेतु - ₹25
दो प्रतियोगिताओं हेतु - ₹40
तीन प्रतियोगिताओं हेतु - ₹60

📌 *दिनाँक - 26 मई 2023 (शुक्रवार)*
📌 *समय - 2 बजे*
📌 *स्थान - कॉन्क्लेव सेन्टर*

🖇️ *फॉर्म लिंक--* https://forms.gle/5f2nJ14vYpmPbbRE8

📌 *जानकारी हेतु संपर्क करें--*
रुद्राक्ष शुक्ला - 8989484091
अथर्व श्रोत्रिय - 8871079163

🖇️ *इंस्टाग्राम--* https://instagram.com/hindiclub.mits?igshid=NTc4MTIwNjQ2YQ==
5/25/23, 6:48 PM - +91 96178 82239: Register ASAP forms will close soon
5/25/23, 7:06 PM - +91 96178 82239: <Media omitted>
5/25/23, 7:23 PM - +91 62634 09068: Good evening everyone, All of you please attempt DSA quizz
5/25/23, 8:51 PM - +91 96178 82239: *_Greetings  from Devtown_*

```We are glad to inform you the list of the top most MNCs  which will be providing you one month guaranteed Virtual internship from MNCs.```

_*Interested candidates kindly join the Group*.

https://chat.whatsapp.com/C8rE8szNNKiEjNJSmmf7nZ
*List of MNCS providing Internship Completion Certificate*_

```Deloitee```
```Walmart```
```JP Morgan```
```AWS```
```TATA```
```MasterCard```
```Accenture```
```Cognizant```
```VISA```
```Infosys```
```Cisco```

_*The above mentioned MNCs will be providing you the Internship and training with placement assistance*._

_There are providing *limited slots* for the coming batches of *May,June and July*_
5/26/23, 12:38 AM - Sheraj IT: <Media omitted>
5/26/23, 12:39 AM - Abhi Patidar IT: <Media omitted>
5/26/23, 12:39 AM - +91 96178 82239: <Media omitted>
5/26/23, 12:40 AM - Sheraj IT: <Media omitted>
5/26/23, 12:40 AM - Sheraj IT: <Media omitted>
5/26/23, 12:41 AM - +91 96178 82239: <Media omitted>
5/26/23, 12:41 AM - +91 95082 12479: <Media omitted>
5/26/23, 12:42 AM - +91 62634 09068: <Media omitted>
5/26/23, 12:42 AM - +91 95082 12479: <Media omitted>
5/26/23, 12:42 AM - +91 96178 82239: <Media omitted>
5/26/23, 12:43 AM - +91 95082 12479: <Media omitted>
5/26/23, 12:43 AM - Sheraj IT: <Media omitted>
5/26/23, 12:44 AM - +91 96178 82239: <Media omitted>
5/26/23, 12:44 AM - +91 95082 12479: <Media omitted>
5/26/23, 12:45 AM - +91 96178 82239: <Media omitted>
5/26/23, 12:45 AM - +91 96178 82239: <Media omitted>
5/26/23, 12:48 AM - +91 95082 12479: <Media omitted>
5/26/23, 12:49 AM - +91 96178 82239: <Media omitted>
5/26/23, 12:53 AM - +91 95082 12479: This message was deleted
5/26/23, 12:53 AM - +91 95082 12479: <Media omitted>
5/26/23, 12:54 AM - +91 96178 82239: This message was deleted
5/26/23, 12:55 AM - +91 96178 82239: <Media omitted>
5/26/23, 12:55 AM - +91 96178 82239: <Media omitted>
5/26/23, 12:55 AM - +91 95082 12479: <Media omitted>
5/26/23, 12:55 AM - +91 95082 12479: <Media omitted>
5/26/23, 12:56 AM - +91 96178 82239: <Media omitted>
5/26/23, 1:07 AM - +91 95082 12479: <Media omitted>
5/26/23, 1:08 AM - +91 96178 82239: <Media omitted>
5/26/23, 11:27 AM - Sagar IT: <Media omitted>
5/26/23, 6:35 PM - +91 62634 09068: *INVITATION:*
*Internship cum Industrial Training with LIVE Project*

*PRAEDICO GLOBAL RESEARCH PRIVATE LIMITED*
*_"A Government Seed Funded Company"_*

*Dear Student,*
If you are worried about your career.
If you are searching for an internship.
If you would like to start your career in the IT field.
If you would like to be a Full Stack Developer with Advance Technology(ies).
If you would like to work on Live Projects.

*1. MERN (MongoDB, ExpressJS, ReactJS, NodeJS)*
*2. Python with Django & Data Science*

JOIN WITH US
*START DATE :* 29-05-2023
*MODE :* ONLINE/OFFLINE
*TIME :* 09:00AM
*DAYS :* Regular (Monday to Friday)
*LINK for ONLINE : http://meet.google.com/vrx-kpzi-eei*
*Gwalior Branch Address for OFFLINE :* First floor, Garima Arcade, MLB Road, Shinde ki Chhawani, Gwalior

*Thanks & Regards*
Team - Praedico Global Research Pvt. Ltd.
Call or WhatsApp for more Details - 8319335916
5/26/23, 6:39 PM - +91 95082 12479: <Media omitted>
5/26/23, 6:39 PM - +91 95082 12479: As per the academic calendar of UG I year (II semesters), the summer internship program (SIP-I) is going to be organized from 19th June to 30th June 2023(excluding Saturday and Sunday).

The registration for the modules will be going to start as per the given schedule on the online portal

Activity

Date

Time

Mock Registration

29/05/2023

12:00 PM onwards

Actual Registration

01/06/2023

12:00 PM onwards

Link for Registration /Mock Drill:      https://nec.mitsgwalior.in


5/26/23, 6:52 PM - Sheraj IT: Avi to demo registration h ..
5/26/23, 6:53 PM - +91 95082 12479: Registration 1 se start h.
5/26/23, 6:53 PM - +91 95082 12479: Nd ye compulsory h sb ko krna parega
5/26/23, 6:53 PM - +91 95082 12479: Iske kux points milte h
5/26/23, 6:53 PM - Arth: Kya hai
5/26/23, 6:53 PM - +91 95082 12479: Summer internship
5/26/23, 7:20 PM - +91 88272 90625: inme se online kon konse h
5/26/23, 7:26 PM - +91 95082 12479: Saare online hi h
5/26/23, 7:26 PM - +91 95082 12479: Offline koi nhi h
5/27/23, 3:15 PM - +91 96178 82239: <Media omitted>
5/27/23, 3:15 PM - +91 96178 82239: Dbms 7
5/27/23, 3:30 PM - Sheraj IT: <Media omitted>
5/27/23, 3:32 PM - +91 96178 82239: Ye math ki quiz to shuru hote hi khatam ho gyi 😂
5/27/23, 3:33 PM - Sheraj IT: 😅😅
5/27/23, 10:57 PM - +91 88272 90625: skilled based project que list share kardo
5/27/23, 10:57 PM - +91 88272 90625: skill*
5/27/23, 11:02 PM - +91 96178 82239: <Media omitted>
5/28/23, 12:07 AM - +91 96178 82239: Happy birthday @917310530803
5/28/23, 12:09 AM - Anmol Tiwari IT: Happy birthday @917310530803
5/28/23, 12:10 AM - +91 96910 98932: Akshat Happy birthday 🎂🎉🎊✨
5/28/23, 12:11 AM - Arth: Happy birthday @917310530803 🥳🥳
5/28/23, 12:13 AM - Sheraj IT: HAPPY BIRTHDAY @917310530803 Bhai🥂🎂🥳🍾
5/28/23, 12:13 AM - Pranav IT: Happy birthday @917310530803 bhai🥳🎊🎉
5/28/23, 12:14 AM - +91 97702 70975: Happy birthday @917310530803
5/28/23, 12:16 AM - +91 62634 09068: Happiest birthday @917310530803 ✨🤩
5/28/23, 12:24 AM - Bhavesh IT: Happy birthday @917310530803  bhai 🎉🎉🥳✨
5/28/23, 12:30 AM - +91 96691 01981: Happy birthday @917310530803  🤩
5/28/23, 12:48 AM - Vivek IT: Happy birthday @917310530803
5/28/23, 12:54 AM - Abhi Patidar IT: Happy birthday @917310530803 🎂🥂
5/28/23, 1:26 AM - +91 93431 43604: Happy Birthday @917310530803 ✨🎂❤️
5/28/23, 2:27 AM - +91 95082 12479: Happiest birthday @917310530803 🥂🥳✨
5/28/23, 2:37 AM - Aditya Batchmate: Happy Birthday @917310530803  🎉🥳
5/28/23, 2:57 AM - +91 94071 87736: Happiest Birthday @917310530803 🎊🎉🥳
5/28/23, 2:58 AM - Prithviraj Chauhan: Happy Birthday @917310530803 🥳🌷🎂🥂
5/28/23, 5:13 AM - Siddhu Moose Wala: Happy Birthday @917310530803 bhai
5/28/23, 7:07 AM - +91 99933 10158: Happy birthday @917310530803
5/28/23, 7:07 AM - +91 99933 10158: This message was deleted
5/28/23, 7:26 AM - Tanay IT: Happy Birthday Bhai @917310530803 🥳🍻🎂
5/28/23, 7:51 AM - Vicky Donar: Happy birthday Akshat Jain 🎂🎉🥳
5/28/23, 8:00 AM - +91 79744 92064: Happy birthday @akshat🥳🥳
5/28/23, 8:01 AM - +91 94075 90087: Happy Birthday @917310530803 🥳🎂
5/28/23, 8:13 AM - Dhurv IT: Happy birthday @917310530803 🥳🥳
5/28/23, 8:20 AM - +91 84355 04472: Happy birthday @917310530803 🎉🎂
5/28/23, 8:37 AM - +91 93292 94247: Happy birthday🥳🎂 @917310530803
5/28/23, 8:46 AM - +91 74896 68532: Happy birthday @917310530803 bro🥳
5/28/23, 9:23 AM - Sakshie IT: Happy birthday @917310530803  🎊🥳
5/28/23, 10:05 AM - Kunal IT: happy birthtday Akshat bro 🎉🥳
5/28/23, 10:48 AM - +91 77248 81647: Happy Birthday akshat bhai 🎉🥳☺️
5/28/23, 10:50 AM - Arth: <Media omitted>
5/28/23, 10:50 AM - Arth: <Media omitted>
5/28/23, 10:54 AM - +91 93011 56061: Happy Birthday akshat🎊🎉..
5/28/23, 11:29 AM - +91 79749 69295: Happy Birthday @917310530803 🎉🎉
5/28/23, 11:33 AM - +91 88274 22204: Happy birthday Akshat 🫂🥳🎂
5/28/23, 11:35 AM - +91 62688 18798: Happy birthday 🥳@917310530803
5/28/23, 11:39 AM - Deepanshu (IT): Happy Birthday @917310530803 🥳🎂🎉
5/28/23, 12:08 PM - +91 93299 05330: Happy birthday @917310530803 🎉🎉
5/28/23, 12:35 PM - +91 88272 90625: happy birthday @917310530803
5/28/23, 4:46 PM - +91 96178 82239: <Media omitted>
5/29/23, 12:04 AM - +91 73105 30803: Thank you so much everyone for making my birthday memorable through your warm wishes and blessings 😊💫❤️
5/29/23, 12:30 PM - Bhumika IT: Jise bhi cso ki attendance lagani ho sir k pas ake lga lena.
5/29/23, 12:33 PM - +91 62634 09068: Sir ne bola hai kya esa
5/29/23, 12:33 PM - Bhumika IT: Hn
5/29/23, 1:13 PM - Arth: Hn bola
5/30/23, 1:39 PM - +91 93431 43604: Yrr koi agr aaj batch B se lab jaa rha ho to meri attendance laga dena plz😇
5/31/23, 3:56 PM - +91 62634 09068: <Media omitted>
5/31/23, 4:15 PM - +91 62634 09068: https://youtube.com/playlist?list=PLaN0KILFgR6g5Imw7r6Xw2F3Ue1mXqu2S

You can check out this playlist.
Some questions of Unit 1 and Unit 2 are solved and explained in it.
5/31/23, 4:19 PM - Arth: Ooo very good yrr 🫡🫡
5/31/23, 5:20 PM - +91 62634 09068: Tomorrow there will be chemistry class from 12 - 1pm in chemistry lab ....
6/1/23, 8:02 AM - +91 96178 82239: Koi CSO ki jaye to proxy laga dena
6/1/23, 12:07 PM - Bhumika IT: Koi chem. Gya ?
6/1/23, 12:37 PM - Arth: This message was deleted
6/1/23, 4:13 PM - Abhi Patidar IT added ~ Harshit
6/2/23, 1:28 AM - +91 96178 82239: <Media omitted>
6/2/23, 1:34 AM - Tanay IT: <Media omitted>
6/2/23, 2:14 AM - Anmol Tiwari IT: This message was deleted
6/2/23, 11:09 AM - +91 88241 93558: Both dsa and python labs are in ds1 lab
6/2/23, 1:38 PM - Abhi Patidar IT added Vivek IT
6/3/23, 2:24 AM - Bhumika IT: guys, is bar mid sem 2 ka syllabus pta h ky kisiko
6/3/23, 2:24 AM - Bhumika IT: maths aur chem ka??
6/3/23, 2:26 AM - Pushkal Mishra It: No
6/3/23, 2:26 AM - Bhumika IT: aur m1 ka syllabus h ky?
6/3/23, 2:26 AM - +91 96178 82239: Soja
6/3/23, 2:26 AM - Bhumika IT: tu kyu jag raha h
6/3/23, 2:26 AM - Pushkal Mishra It: 🫂
6/3/23, 2:26 AM - +91 96178 82239: Mujhe phone karke uthaya gya hai🥲🥲
6/3/23, 2:27 AM - Bhumika IT: pushkal, dont you dare
hoshyar tu bhi toh jg hi raha h
6/3/23, 2:27 AM - Bhumika IT: kisnee😏😏
6/3/23, 2:27 AM - Pushkal Mishra It: 😂
6/3/23, 2:27 AM - +91 96178 82239: Dm mei btata hun 😅
6/3/23, 2:27 AM - Bhumika IT: yaar koi pdha do m1 aur chem
6/3/23, 2:28 AM - Bhumika IT: tu kr dm
6/3/23, 2:28 AM - Pushkal Mishra It: Mari good night 5 baja tak hoti ha  daily
6/3/23, 2:28 AM - +91 96178 82239: Gajendra kushwah on Yt and pushkal mishra of IT
6/3/23, 2:28 AM - Bhumika IT: that sounds FUCKED UP
6/3/23, 2:28 AM - Bhumika IT: isn't it gajendra purohit
6/3/23, 2:28 AM - Sheraj IT: So jaao bacho 🍼👶....
6/3/23, 2:28 AM - Bhumika IT: and kalpush mishra?
6/3/23, 2:28 AM - +91 96178 82239: Pada kaun hai usse jo naam pta hoga 😂
6/3/23, 2:28 AM - Bhumika IT: back at you
6/3/23, 2:29 AM - +91 96178 82239: Goli beta masti nhi
6/3/23, 2:29 AM - Bhumika IT: hai hi dhor.. yr bhut badi badi playlist h
6/3/23, 2:29 AM - Sheraj IT: <Media omitted>
6/3/23, 2:29 AM - Pushkal Mishra It: Naaa
6/3/23, 2:29 AM - Bhumika IT: arre munna tu fir uth gya, anuj ko bol lori gaake sula dega
6/3/23, 2:29 AM - +91 96178 82239: I know that I am an idiot 😂
6/3/23, 2:30 AM - Bhumika IT: +1
6/3/23, 2:30 AM - Sheraj IT: Anuj to pehle hi so gya..
6/3/23, 2:30 AM - Bhumika IT: tu bhi jake so ja
6/3/23, 2:30 AM - Sheraj IT: Munni neend ni aa ri kya🍼🍼
6/3/23, 2:30 AM - Bhumika IT: <Media omitted>
6/3/23, 2:31 AM - Bhumika IT: nhi, tu aake lori gaega ky munna
6/3/23, 2:31 AM - +91 93431 43604: Kitna padhegi bhumika issi saal 1crore ka placement lelegi kya🥲
6/3/23, 2:31 AM - Bhumika IT: bhai mere fail ho re hain yaha ham
6/3/23, 2:31 AM - Sheraj IT: Bhumika full josshh..h
6/3/23, 2:31 AM - Bhumika IT: aur nind bhi toh lage
6/3/23, 2:32 AM - Bhumika IT: ft. sheraj sharif IT
6/3/23, 2:32 AM - +91 93431 43604: YouTube music ki jagah Spotify pr sunno neend aajayegi 😂
6/3/23, 2:32 AM - Bhumika IT: tujhe kese pata m yt music use kr ri hu
6/3/23, 2:32 AM - Sheraj IT: Usme adds aate h😅
6/3/23, 2:32 AM - +91 93431 43604: 😎😎
6/3/23, 2:32 AM - Bhumika IT: arre garib premium premium
6/3/23, 2:32 AM - +91 96178 82239: Premium account le lo
6/3/23, 2:32 AM - Bhumika IT: dayum stalkers

In [141]:
print(type(data))

<class 'str'>

In [142]:
# regular expression for identfiy the pattern 
# go on regex101.com print a sample message and got your regular expression


actual_message = r"^(\d{1,2}/\d{1,2}/\d{2}), (\d{1,2}:\d{2})\s?([AP]M) - ([A-Za-z\s]+): (.+)$"

pattern  = "\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}\s?[AP]M\s-\s"
time_slot ="?[AP]M\s-\s"

In [143]:
message =re.split(pattern,data)[1:] # [1:] as empty list is apperaing in it

message

['Messages and calls are end-to-end encrypted. No one outside of this chat, not even WhatsApp, can read or listen to them. Tap to learn more.\n',
 '+91 77248 81647: Happy birthday Nisha 🥳🎉\n',
 '+91 77248 81647: Happy birthday prithviraj 🎉🥳\n',
 '+91 89899 71799: Happiest Birthday to you both 🎉🎉 @919669101981 @917697045869\n',
 'Bhumika IT: Happy birthday Nisha and prithviraj\n',
 '+91 79749 69295: Happy Birthday @919669101981 🎁🎁🎉\n',
 '+91 74896 68532: Happy birthday @919669101981 and @917697045869   🥳🥳\n',
 '+91 96910 98932: Happy Birthday @919669101981🎂🎉🎊\n',
 '+91 96910 98932: @917697045869 Happy Birthday ✨✌️\n',
 'Yuvika Nagle IT: Happy Birthday @919669101981 ✨🥳🥳🥳\n',
 '+91 94075 90087: Happy Birthday @919669101981 @917697045869 🎂✨🥳🥳\n',
 'Pushkal Mishra It: Happy birthday Nisha and Prithviraj 🥳🥳\n',
 '+91 93292 94247: Happy birthday🥳🎂 @919669101981 \n@917697045869\n',
 '+91 73105 30803: Happy Birthday @919669101981  🥳🥳\n',
 'Kunal IT: Happ birthday Nisha 🥳🥳✨\n',
 'Kunal IT: And Happy birthday prithviraj ✨✨🥳\n',
 '+91 62688 18798: Happy birthday 🥳@917697045869\n',
 '+91 62688 18798: Happy birthday 🥳@919669101981\n',
 'Vivek IT: Happy birthday @917697045869\n',
 'Vivek IT: Happy birthday @919669101981\n',
 '+91 94071 87736: Happy Birthday @919669101981 nd @917697045869 🥳🥳\n',
 '+91 93011 56061: Happy Birthday @919669101981🎉 and @917697045869 🎊\n',
 'Ashutosh IT: Happy birthday nisha  and  prithviraj 🎂🎉🎁\n',
 '+91 91749 93905: Happy birthday @919669101981  and @917697045869 ✨🌈💥\n',
 '+91 93299 05330: Happy birthday @917697045869 🎉🎉\n',
 '+91 93299 05330: Happy birthday @919669101981 🎉🎉\n',
 'Dhurv IT: Happy birthday Prithviraj and Nisha 🥳🥳\n',
 '~GOURAV IT: Happy Birthday @917697045869 and @919669101981 🎉\n',
 '+91 96178 82239: Happy birthday @917697045869\n',
 '+91 96178 82239: Happy birthday @919669101981\n',
 '+91 79744 92064: Happy birthday @917697045869 and @919669101981 🥳🥳\n',
 '+91 96178 82239: This message was deleted\n',
 '+91 96691 01981: Thank you so much everyone❤️\n',
 '+91 96178 82239: <Media omitted>\n',
 '+91 96178 82239: <Media omitted>\n',
 '+91 96178 82239: <Media omitted>\n',
 '+91 96178 82239: <Media omitted>\n',
 '+91 96178 82239: <Media omitted>\n',
 '+91 79744 92064: This message was deleted\n',
 'Pushkal Mishra It: Kha tho sahi raha ho\n',
 'Pushkal Mishra It: Per option ma he nahi ha\n',
 '+91 96178 82239: Sir ko bheja hai wo 😅\n',
 'Prithviraj Chauhan: Thank you so much everyone for wishes❤️🎂💫🥳\n',
 '+91 96178 82239: Meri proxy laga dena koi\n',
 'Bhumika IT: +1\n',
 'Sheraj IT: Tum kaise lga skti hi..tum to batch A me ho 🙄\n',
 'Arth: Indirectly bol rhi hai meri bhi laga dena\n',
 'Sheraj IT: -1\n',
 'Sheraj IT: Ab tu v batch A me h..\n',
 '+91 93011 56061: 🇮🇳✨\n*नमन है हर क्रांतिवीर और उनकी अमर कहानियों को,*\n*नहीं भूलेंगे भारत माँ तेरे सपूतों और उनकी क़ुर्बानियों को।*\n🇮🇳✨\n\nनमस्कार साथियों !!💫\n\nहिन्दी क्लब एमआईटीएस एवं अखिल भारतीय साहित्य परिषद के संयुक्त तत्वाधान में हमारे स्वतंत्रता संग्राम के क्रांतिवीरों को श्रद्धांजलि अर्पित करने एवं आप सभी को उनके बारे में जागरूक करने के उद्देश्य से *याद करो क़ुर्बानी* कार्यक्रम का आयोजन होने जा रहा है जिसके अंतर्गत 3 प्रतियोगिताओं का आयोजन होना है- \n\n🇮🇳 *\'कहानी वीरों की\'* जिसके अंतर्गत प्रतिभागी को किसी "ऐसे क्रांतिवीर के बारे में वक्तव्य देना होगा जिनके बारे में हम सभी को कम ज्ञात है या जिन्हें उनके योगदान के अनुरूप पहचान नहीं मिली है"।\n\n🇮🇳 *\'क्रांति Quiz\'* जिसके अंतर्गत दो चरणों में प्रश्नोत्तरी(पहला चरण लिखित एवं दूसरा चरण मौखिक) "भारतीय स्वतंत्रता संग्राम एवं उसके क्रांतिवीर" इस विषय पर आयोजित की जाएगी। \n\n🇮🇳 *\'कला से क्रांति\'* जिसके अंतर्गत "स्वतंत्रता संग्राम कालिक दृश्य" या "स्वतंत्रता क्रांतिवीर" इन दो विषयों पर चित्रकला प्रतियोगिता का आयोजन किया जाएगा।\n\n📎विजेताओं को *आकर्षक उपहार एवं प्रमाण पत्र* प्रदान किए जाएंगे साथ ही सभी प्रतिभागियों को *ई प्रमाण पत्र* प्रदान किए जाएंगे।\n\n📎 *पंजीकरण शुल्क--*\nएक प्रतियोगिता हेतु - ₹25 \nदो प्रतियोगिताओं हेतु - ₹40 \nतीन प्रतियोगिताओं हेतु - ₹60\n\n📌 *दिनाँक - 26 मई 2023 (शुक्रवार)*\n📌 *समय - 2 बजे*\n📌 *स्थान - कॉन्क्लेव सेन्टर*\n\n🖇️ *फॉर्म लिंक--* https://forms.gle/5f2nJ14vYpmPbbRE8\n\n📌 *जानकारी हेतु संपर्क करें--*\nरुद्राक्ष शुक्ला - 8989484091\nअथर्व श्रोत्रिय - 8871079163\n\n🖇️ *इंस्टाग्राम--* https://instagram.com/hindiclub.mits?igshid=NTc4MTIwNjQ2YQ==\n',
 '+91 93011 56061: <Media omitted>\n',
 '+91 62634 09068: Good evening everyone,\nPlease attempt the quiz before 8pm ...\n',
 '+91 96178 82239: _आओ जाने "याद करो कुर्बानी" को_\n\nhttps://www.instagram.com/p/CsmMm10IgWM/?igshid=MzRlODBiNWFlZA==\n\nLINK - https://forms.gle/5f2nJ14vYpmPbbRE8\n',
 '+91 96178 82239: If anyone interested dm me\n',
 '+91 96178 82239: <Media omitted>\n',
 '+91 96178 82239: Please consider this as the certificate is national level worth 5 credits per competition so if you participate in three it will be 15 points and the winners will be honoured by Jyotriadhitya scindia on 11 June in Shivpuri\n',
 '+91 96178 82239: For more details you can contact me rudraksh Or atharav\n',
 '+91 96178 82239: Itte credit CR ke nhi hote 😅\n',
 '+91 62634 09068: Good evening everyone,\nTomorrow there will be chemistry class from 12pm - 1 pm...\n',
 '+91 62634 09068: <Media omitted>\n',
 '+91 62634 09068: Guys please attempt DSA quizz before 8 ....\n',
 'Arth: Mari Chhori chhoro se kam hai kee 😎\n',
 '+91 93431 43604: null\n',
 'Pushkal Mishra It: <Media omitted>\n',
 'Siddhu Moose Wala: Last 40 saal me dekh lo  rairly 10 me eak do hai kisi kisi year\n',
 '+91 93431 43604: Woi bhai! \nBoards aur UPSC jaise ratne ki cheezo me hi charche me rehti h 🤣\n',
 'Arth: Bol na pdhta hai\n',
 '+91 96178 82239: <Media omitted>\n',
 '+91 96178 82239: <Media omitted>\n',
 '+91 96178 82239: guys we will close the form at 8 PM Today so plz register ASAP\n',
 '+91 62634 09068: Guys chemistry class kahan ho rhi hai\n',
 '+91 62634 09068: 🥲🥲🥲\n',
 '+91 62634 09068: Koi toh bta doo😣😣\n',
 'Divyansh Senger IT: 112\n',
 '+91 96178 82239: 🇮🇳✨\n*नमन है हर क्रांतिवीर और उनकी अमर कहानियों को,*\n*नहीं भूलेंगे भारत माँ तेरे सपूतों और उनकी क़ुर्बानियों को।*\n🇮🇳✨\n\nनमस्कार साथियों !!💫\n\nहिन्दी क्लब एमआईटीएस एवं अखिल भारतीय साहित्य परिषद के संयुक्त तत्वाधान में हमारे स्वतंत्रता संग्राम के क्रांतिवीरों को श्रद्धांजलि अर्पित करने एवं आप सभी को उनके बारे में जागरूक करने के उद्देश्य से *याद करो क़ुर्बानी* कार्यक्रम का आयोजन होने जा रहा है जिसके अंतर्गत 3 प्रतियोगिताओं का आयोजन होना है- \n\n🇮🇳 *\'कहानी वीरों की\'* जिसके अंतर्गत प्रतिभागी को किसी "ऐसे क्रांतिवीर के बारे में वक्तव्य देना होगा जिनके बारे में हम सभी को कम ज्ञात है या जिन्हें उनके योगदान के अनुरूप पहचान नहीं मिली है"।\n\n🇮🇳 *\'क्रांति Quiz\'* जिसके अंतर्गत दो चरणों में प्रश्नोत्तरी(पहला चरण लिखित एवं दूसरा चरण मौखिक) "भारतीय स्वतंत्रता संग्राम एवं उसके क्रांतिवीर" इस विषय पर आयोजित की जाएगी। \n\n🇮🇳 *\'कला से क्रांति\'* जिसके अंतर्गत "स्वतंत्रता संग्राम कालिक दृश्य" या "स्वतंत्रता क्रांतिवीर" इन दो विषयों पर चित्रकला प्रतियोगिता का आयोजन किया जाएगा।\n\n📎विजेताओं को *आकर्षक उपहार एवं प्रमाण पत्र* प्रदान किए जाएंगे साथ ही सभी प्रतिभागियों को *ई प्रमाण पत्र* प्रदान किए जाएंगे।\n\n📎 *पंजीकरण शुल्क--*\nएक प्रतियोगिता हेतु - ₹25 \nदो प्रतियोगिताओं हेतु - ₹40 \nतीन प्रतियोगिताओं हेतु - ₹60\n\n📌 *दिनाँक - 26 मई 2023 (शुक्रवार)*\n📌 *समय - 2 बजे*\n📌 *स्थान - कॉन्क्लेव सेन्टर*\n\n🖇️ *फॉर्म लिंक--* https://forms.gle/5f2nJ14vYpmPbbRE8\n\n📌 *जानकारी हेतु संपर्क करें--*\nरुद्राक्ष शुक्ला - 8989484091\nअथर्व श्रोत्रिय - 8871079163\n\n🖇️ *इंस्टाग्राम--* https://instagram.com/hindiclub.mits?igshid=NTc4MTIwNjQ2YQ==\n',
 '+91 96178 82239: Register ASAP forms will close soon\n',
 '+91 96178 82239: <Media omitted>\n',
 '+91 62634 09068: Good evening everyone, All of you please attempt DSA quizz\n',
 '+91 96178 82239: *_Greetings  from Devtown_*\n\n```We are glad to inform you the list of the top most MNCs  which will be providing you one month guaranteed Virtual internship from MNCs.```\n\n_*Interested candidates kindly join the Group*.\n\nhttps://chat.whatsapp.com/C8rE8szNNKiEjNJSmmf7nZ\n*List of MNCS providing Internship Completion Certificate*_\n\n```Deloitee```\n```Walmart```\n```JP Morgan```\n```AWS```\n```TATA```\n```MasterCard```\n```Accenture```\n```Cognizant```\n```VISA```\n```Infosys```\n```Cisco```\n\n_*The above mentioned MNCs will be providing you the Internship and training with placement assistance*._\n\n_There are providing *limited slots* for the coming batches of *May,June and July*_\n',
 'Sheraj IT: <Media omitted>\n',
 'Abhi Patidar IT: <Media omitted>\n',
 '+91 96178 82239: <Media omitted>\n',
 'Sheraj IT: <Media omitted>\n',
 'Sheraj IT: <Media omitted>\n',
 '+91 96178 82239: <Media omitted>\n',
 '+91 95082 12479: <Media omitted>\n',
 '+91 62634 09068: <Media omitted>\n',
 '+91 95082 12479: <Media omitted>\n',
 '+91 96178 82239: <Media omitted>\n',
 '+91 95082 12479: <Media omitted>\n',
 'Sheraj IT: <Media omitted>\n',
 '+91 96178 82239: <Media omitted>\n',
 '+91 95082 12479: <Media omitted>\n',
 '+91 96178 82239: <Media omitted>\n',
 '+91 96178 82239: <Media omitted>\n',
 '+91 95082 12479: <Media omitted>\n',
 '+91 96178 82239: <Media omitted>\n',
 '+91 95082 12479: This message was deleted\n',
 '+91 95082 12479: <Media omitted>\n',
 '+91 96178 82239: This message was deleted\n',
 '+91 96178 82239: <Media omitted>\n',
 '+91 96178 82239: <Media omitted>\n',
 '+91 95082 12479: <Media omitted>\n',
 '+91 95082 12479: <Media omitted>\n',
 '+91 96178 82239: <Media omitted>\n',
 '+91 95082 12479: <Media omitted>\n',
 '+91 96178 82239: <Media omitted>\n',
 'Sagar IT: <Media omitted>\n',
 '+91 62634 09068: *INVITATION:*\n*Internship cum Industrial Training with LIVE Project*\n\n*PRAEDICO GLOBAL RESEARCH PRIVATE LIMITED*\n*_"A Government Seed Funded Company"_* \n\n*Dear Student,* \nIf you are worried about your career.\nIf you are searching for an internship.\nIf you would like to start your career in the IT field.\nIf you would like to be a Full Stack Developer with Advance Technology(ies).\nIf you would like to work on Live Projects.\n\n*1. MERN (MongoDB, ExpressJS, ReactJS, NodeJS)* \n*2. Python with Django & Data Science*\n\nJOIN WITH US\n*START DATE :* 29-05-2023\n*MODE :* ONLINE/OFFLINE \n*TIME :* 09:00AM\n*DAYS :* Regular (Monday to Friday)\n*LINK for ONLINE : http://meet.google.com/vrx-kpzi-eei*\n*Gwalior Branch Address for OFFLINE :* First floor, Garima Arcade, MLB Road, Shinde ki Chhawani, Gwalior \n\n*Thanks & Regards*\nTeam - Praedico Global Research Pvt. Ltd.\nCall or WhatsApp for more Details - 8319335916\n',
 '+91 95082 12479: <Media omitted>\n',
 '+91 95082 12479: As per the academic calendar of UG I year (II semesters), the summer internship program (SIP-I) is going to be organized from 19th June to 30th June 2023(excluding Saturday and Sunday).\n\nThe registration for the modules will be going to start as per the given schedule on the online portal\n\nActivity\n\nDate\n\nTime\n\nMock Registration\n\n29/05/2023\n\n12:00 PM onwards\n\nActual Registration\n\n01/06/2023\n\n12:00 PM onwards\n\nLink for Registration /Mock Drill:\xa0\xa0\xa0\xa0 \xa0https://nec.mitsgwalior.in \xa0\xa0\n\n\xa0\n',
 'Sheraj IT: Avi to demo registration h ..\n',
 '+91 95082 12479: Registration 1 se start h.\n',
 '+91 95082 12479: Nd ye compulsory h sb ko krna parega\n',
 '+91 95082 12479: Iske kux points milte h\n',
 'Arth: Kya hai\n',
 '+91 95082 12479: Summer internship\n',
 '+91 88272 90625: inme se online kon konse h\n',
 '+91 95082 12479: Saare online hi h\n',
 '+91 95082 12479: Offline koi nhi h\n',
 '+91 96178 82239: <Media omitted>\n',
 '+91 96178 82239: Dbms 7\n',
 'Sheraj IT: <Media omitted>\n',
 '+91 96178 82239: Ye math ki quiz to shuru hote hi khatam ho gyi 😂\n',
 'Sheraj IT: 😅😅\n',
 '+91 88272 90625: skilled based project que list share kardo\n',
 '+91 88272 90625: skill*\n',
 '+91 96178 82239: <Media omitted>\n',
 '+91 96178 82239: Happy birthday @917310530803\n',
 'Anmol Tiwari IT: Happy birthday @917310530803\n',
 '+91 96910 98932: Akshat Happy birthday 🎂🎉🎊✨\n',
 'Arth: Happy birthday @917310530803 🥳🥳\n',
 'Sheraj IT: HAPPY BIRTHDAY @917310530803 Bhai🥂🎂🥳🍾\n',
 'Pranav IT: Happy birthday @917310530803 bhai🥳🎊🎉\n',
 '+91 97702 70975: Happy birthday @917310530803\n',
 '+91 62634 09068: Happiest birthday @917310530803 ✨🤩\n',
 'Bhavesh IT: Happy birthday @917310530803  bhai 🎉🎉🥳✨\n',
 '+91 96691 01981: Happy birthday @917310530803  🤩\n',
 'Vivek IT: Happy birthday @917310530803\n',
 'Abhi Patidar IT: Happy birthday @917310530803 🎂🥂\n',
 '+91 93431 43604: Happy Birthday @917310530803 ✨🎂❤️\n',
 '+91 95082 12479: Happiest birthday @917310530803 🥂🥳✨\n',
 'Aditya Batchmate: Happy Birthday @917310530803  🎉🥳\n',
 '+91 94071 87736: Happiest Birthday @917310530803 🎊🎉🥳\n',
 'Prithviraj Chauhan: Happy Birthday @917310530803 🥳🌷🎂🥂\n',
 'Siddhu Moose Wala: Happy Birthday @917310530803 bhai\n',
 '+91 99933 10158: Happy birthday @917310530803\n',
 '+91 99933 10158: This message was deleted\n',
 'Tanay IT: Happy Birthday Bhai @917310530803 🥳🍻🎂\n',
 'Vicky Donar: Happy birthday Akshat Jain 🎂🎉🥳\n',
 '+91 79744 92064: Happy birthday @akshat🥳🥳\n',
 '+91 94075 90087: Happy Birthday @917310530803 🥳🎂\n',
 'Dhurv IT: Happy birthday @917310530803 🥳🥳\n',
 '+91 84355 04472: Happy birthday @917310530803 🎉🎂\n',
 '+91 93292 94247: Happy birthday🥳🎂 @917310530803\n',
 '+91 74896 68532: Happy birthday @917310530803 bro🥳\n',
 'Sakshie IT: Happy birthday @917310530803  🎊🥳\n',
 'Kunal IT: happy birthtday Akshat bro 🎉🥳\n',
 '+91 77248 81647: Happy Birthday akshat bhai 🎉🥳☺️\n',
 'Arth: <Media omitted>\n',
 'Arth: <Media omitted>\n',
 '+91 93011 56061: Happy Birthday akshat🎊🎉..\n',
 '+91 79749 69295: Happy Birthday @917310530803 🎉🎉\n',
 '+91 88274 22204: Happy birthday Akshat 🫂🥳🎂\n',
 '+91 62688 18798: Happy birthday 🥳@917310530803\n',
 'Deepanshu (IT): Happy Birthday @917310530803 🥳🎂🎉\n',
 '+91 93299 05330: Happy birthday @917310530803 🎉🎉\n',
 '+91 88272 90625: happy birthday @917310530803\n',
 '+91 96178 82239: <Media omitted>\n',
 '+91 73105 30803: Thank you so much everyone for making my birthday memorable through your warm wishes and blessings 😊💫❤️\n',
 'Bhumika IT: Jise bhi cso ki attendance lagani ho sir k pas ake lga lena.\n',
 '+91 62634 09068: Sir ne bola hai kya esa\n',
 'Bhumika IT: Hn\n',
 'Arth: Hn bola\n',
 '+91 93431 43604: Yrr koi agr aaj batch B se lab jaa rha ho to meri attendance laga dena plz😇\n',
 '+91 62634 09068: <Media omitted>\n',
 '+91 62634 09068: https://youtube.com/playlist?list=PLaN0KILFgR6g5Imw7r6Xw2F3Ue1mXqu2S \n\nYou can check out this playlist.\nSome questions of Unit 1 and Unit 2 are solved and explained in it.\n',
 'Arth: Ooo very good yrr 🫡🫡\n',
 '+91 62634 09068: Tomorrow there will be chemistry class from 12 - 1pm in chemistry lab ....\n',
 '+91 96178 82239: Koi CSO ki jaye to proxy laga dena\n',
 'Bhumika IT: Koi chem. Gya ?\n',
 'Arth: This message was deleted\n',
 'Abhi Patidar IT added ~\u202fHarshit\n',
 '+91 96178 82239: <Media omitted>\n',
 'Tanay IT: <Media omitted>\n',
 'Anmol Tiwari IT: This message was deleted\n',
 '+91 88241 93558: Both dsa and python labs are in ds1 lab\n',
 'Abhi Patidar IT added Vivek IT\n',
 'Bhumika IT: guys, is bar mid sem 2 ka syllabus pta h ky kisiko\n',
 'Bhumika IT: maths aur chem ka??\n',
 'Pushkal Mishra It: No\n',
 'Bhumika IT: aur m1 ka syllabus h ky?\n',
 '+91 96178 82239: Soja\n',
 'Bhumika IT: tu kyu jag raha h\n',
 'Pushkal Mishra It: 🫂\n',
 '+91 96178 82239: Mujhe phone karke uthaya gya hai🥲🥲\n',
 'Bhumika IT: pushkal, dont you dare \nhoshyar tu bhi toh jg hi raha h\n',
 'Bhumika IT: kisnee😏😏\n',
 'Pushkal Mishra It: 😂\n',
 '+91 96178 82239: Dm mei btata hun 😅\n',
 'Bhumika IT: yaar koi pdha do m1 aur chem\n',
 'Bhumika IT: tu kr dm\n',
 'Pushkal Mishra It: Mari good night 5 baja tak hoti ha  daily\n',
 '+91 96178 82239: Gajendra kushwah on Yt and pushkal mishra of IT\n',
 'Bhumika IT: that sounds FUCKED UP\n',
 "Bhumika IT: isn't it gajendra purohit\n",
 'Sheraj IT: So jaao bacho 🍼👶....\n',
 'Bhumika IT: and kalpush mishra?\n',
 '+91 96178 82239: Pada kaun hai usse jo naam pta hoga 😂\n',
 'Bhumika IT: back at you\n',
 '+91 96178 82239: Goli beta masti nhi\n',
 'Bhumika IT: hai hi dhor.. yr bhut badi badi playlist h\n',
 'Sheraj IT: <Media omitted>\n',
 'Pushkal Mishra It: Naaa\n',
 'Bhumika IT: arre munna tu fir uth gya, anuj ko bol lori gaake sula dega\n',
 '+91 96178 82239: I know that I am an idiot 😂\n',
 'Bhumika IT: +1\n',
 'Sheraj IT: Anuj to pehle hi so gya..\n',
 'Bhumika IT: tu bhi jake so ja\n',
 'Sheraj IT: Munni neend ni aa ri kya🍼🍼\n',
 'Bhumika IT: <Media omitted>\n',
 'Bhumika IT: nhi, tu aake lori gaega ky munna\n',
 '+91 93431 43604: Kitna padhegi bhumika issi saal 1crore ka placement lelegi kya🥲\n',
 'Bhumika IT: bhai mere fail ho re hain yaha ham\n',
 'Sheraj IT: Bhumika full josshh..h\n',
 'Bhumika IT: aur nind bhi toh lage\n',
 'Bhumika IT: ft. sheraj sharif IT\n',
 '+91 93431 43604: YouTube music ki jagah Spotify pr sunno neend aajayegi 😂\n',
 'Bhumika IT: tujhe kese pata m yt music use kr ri hu\n',
 'Sheraj IT: Usme adds aate h😅\n',
 '+91 93431 43604: 😎😎\n',
 'Bhumika IT: arre garib premium premium\n',
 '+91 96178 82239: Premium account le lo\n',
 'Bhumika IT: dayum stalkers\n',
 'Bhumika IT: chanda ikattha krke lelete h\n',
 'Sheraj IT: Hamre chacha vidhayak ni h...\n',
 'Bhumika IT: wese back at the orignal ques. koi toh batao paper m kya aana h\n',
 'Sheraj IT: Paper me questions ko aana h😅\n',
 'Sheraj IT: Aur result me andda aana h\n',
 '+91 93431 43604: Iss baat ke liye tanay teri puppy lelega 😂😂\n',
 '+91 96178 82239: Mere kaunse hai student ID lagao saste mein suvidhayen pao\n',
 'Bhumika IT: tera 20 aana h\n',
 'Sheraj IT: Kyun tera mnn bhar diya kya😏😏\n',
 'Bhumika IT: doing the same lol , 6 mahine prime free h abhi toh\n',
 '+91 96178 82239: Badiya\n',
 'Bhumika IT: m1 ka syllabus toh de do hoshyaro\n',
 'Bhumika IT: 🥹🥹\n',
 '+91 93431 43604: Unit 12345\n',
 'Sheraj IT: <Media omitted>\n',
 'Bhumika IT: maar pitne wale km h ritesh tere\n',
 'Sheraj IT: M1 kya h🙄\n',
 '+91 96178 82239: @917067429566 @916263409068  kese cr ho koi kuch mang rha hai aur tum so rhe ho\n',
 'Bhumika IT: Eng. maths\n',
 '+91 93431 43604: Areeh yaar sb padhle tu \nBaad me kaam aajayega\n',
 'Sheraj IT: Tum kaise log ho..itna s syllabus v ni le paa rhe🤦🤦\n',
 '+91 96178 82239: Bol bhi kaun rha hain\n',
 'Bhumika IT: abbe koi de toh\n',
 'Sheraj IT: Beta CR bacho ki madad kro..\n',
 'Abhi Patidar IT: Bhai pata hi nahi hai\n',
 'Sheraj IT: 😎😎\n',
 'Bhumika IT: are yaha 1 unit k L lage h 5 padhu m\n',
 'Abhi Patidar IT: Abhi course chal Raha hai   bataya nahi abhi\n',
 'Sheraj IT: Bahot badhiya 🤣\n',
 'Abhi Patidar IT: DSA me 1,2 ,3,5 unit\n',
 '+91 93431 43604: Course me kya chl rha h🥱\n',
 '+91 96178 82239: https://drive.google.com/file/d/1-ZBRGsdz5-ID7joQ48W66al3j3_Dutic/view?usp=drivesdk\n',
 'Divyansh Senger IT: Mang rhe h to kya raat m v duty kre apni soye nhi bichare\n',
 'Bhumika IT: thanksss\n',
 '+91 96178 82239: Mene ki hai raat mein to haq banta hai 😂\n',
 'Abhi Patidar IT: Haa bhai dekh le yrr\n',
 "Bhumika IT: CR duties bhai, 24'*7 avaialable honi chahitye\n",
 'Bhumika IT: ek night shift pe. ek day shift pe\n',
 'Abhi Patidar IT: Tujhme or mujhe bahut fark hai bhai\n',
 'Sheraj IT: Cr ki duty kya.. hoti shivalik ne change kr di h..\n',
 'Sheraj IT: Ab hmre naye CR constitution me sudhar layenge...\n',
 'Abhi Patidar IT: Bs college time ki hoti hai  but shivalik ne change ki hai toh usko follow kar rahe hai\n',
 '+91 96178 82239: Lao lai\n',
 'Abhi Patidar IT: Dheere dheere khatam kar denge tension na lo\n',
 'Divyansh Senger IT: Isko Chen nhi h abhi se padh legi pura fhir 15 min m paper kr k nikl jati h class m se\n',
 'Bhumika IT: koi toh h jo ye smjhaaa\n',
 '+91 96178 82239: +1\n',
 'Bhumika IT: abbe no. tere zada a re h\n',
 'Sheraj IT: 🤣🤣\n',
 'Bhumika IT: 15 min. nhi 25 leti hu wese\n',
 'Sheraj IT: Talent h mam k😎😎\n',
 'Divyansh Senger IT: Ha 🏆\n',
 'Bhumika IT: arre sir apse kaha ka comparision\n',
 '+91 96178 82239: Pushkal sir padaye the humko\n',
 'Sheraj IT: Koi comparison ni😥\n',
 'Bhumika IT: haan pushkal sir\n',

In [144]:

dates =re.findall(pattern,data)
dates = [i.replace("\u202f"," ") for i in dates]
dates = [i.replace("-","") for i in dates]
dates

['5/22/23, 1:52 AM  ',
 '5/22/23, 1:55 AM  ',
 '5/22/23, 1:56 AM  ',
 '5/22/23, 2:38 AM  ',
 '5/22/23, 5:29 AM  ',
 '5/22/23, 7:25 AM  ',
 '5/22/23, 7:34 AM  ',
 '5/22/23, 7:58 AM  ',
 '5/22/23, 7:59 AM  ',
 '5/22/23, 8:18 AM  ',
 '5/22/23, 8:47 AM  ',
 '5/22/23, 8:49 AM  ',
 '5/22/23, 8:53 AM  ',
 '5/22/23, 10:01 AM  ',
 '5/22/23, 10:03 AM  ',
 '5/22/23, 10:03 AM  ',
 '5/22/23, 10:06 AM  ',
 '5/22/23, 10:07 AM  ',
 '5/22/23, 10:09 AM  ',
 '5/22/23, 10:09 AM  ',
 '5/22/23, 10:22 AM  ',
 '5/22/23, 10:30 AM  ',
 '5/22/23, 10:32 AM  ',
 '5/22/23, 10:40 AM  ',
 '5/22/23, 10:58 AM  ',
 '5/22/23, 10:59 AM  ',
 '5/22/23, 11:03 AM  ',
 '5/22/23, 2:43 PM  ',
 '5/22/23, 3:02 PM  ',
 '5/22/23, 3:02 PM  ',
 '5/22/23, 3:04 PM  ',
 '5/22/23, 5:41 PM  ',
 '5/22/23, 6:02 PM  ',
 '5/22/23, 7:09 PM  ',
 '5/22/23, 7:09 PM  ',
 '5/22/23, 7:09 PM  ',
 '5/22/23, 7:09 PM  ',
 '5/22/23, 7:39 PM  ',
 '5/22/23, 7:40 PM  ',
 '5/22/23, 7:41 PM  ',
 '5/22/23, 7:41 PM  ',
 '5/22/23, 7:41 PM  ',
 '5/22/23, 9:02 PM  ',
 '5/23/23, 8:06 AM  ',
 '5/23/23, 8:10 AM  ',
 '5/23/23, 12:16 PM  ',
 '5/23/23, 12:16 PM  ',
 '5/23/23, 12:17 PM  ',
 '5/23/23, 12:18 PM  ',
 '5/23/23, 6:01 PM  ',
 '5/23/23, 6:01 PM  ',
 '5/23/23, 7:19 PM  ',
 '5/24/23, 5:11 AM  ',
 '5/24/23, 5:11 AM  ',
 '5/24/23, 1:57 PM  ',
 '5/24/23, 2:55 PM  ',
 '5/24/23, 2:56 PM  ',
 '5/24/23, 2:57 PM  ',
 '5/24/23, 4:48 PM  ',
 '5/24/23, 7:10 PM  ',
 '5/24/23, 7:11 PM  ',
 '5/24/23, 7:11 PM  ',
 '5/24/23, 7:28 PM  ',
 '5/24/23, 7:29 PM  ',
 '5/24/23, 7:30 PM  ',
 '5/24/23, 7:32 PM  ',
 '5/24/23, 7:37 PM  ',
 '5/24/23, 7:53 PM  ',
 '5/25/23, 9:41 AM  ',
 '5/25/23, 9:42 AM  ',
 '5/25/23, 12:19 PM  ',
 '5/25/23, 12:19 PM  ',
 '5/25/23, 12:23 PM  ',
 '5/25/23, 12:26 PM  ',
 '5/25/23, 6:40 PM  ',
 '5/25/23, 6:48 PM  ',
 '5/25/23, 7:06 PM  ',
 '5/25/23, 7:23 PM  ',
 '5/25/23, 8:51 PM  ',
 '5/26/23, 12:38 AM  ',
 '5/26/23, 12:39 AM  ',
 '5/26/23, 12:39 AM  ',
 '5/26/23, 12:40 AM  ',
 '5/26/23, 12:40 AM  ',
 '5/26/23, 12:41 AM  ',
 '5/26/23, 12:41 AM  ',
 '5/26/23, 12:42 AM  ',
 '5/26/23, 12:42 AM  ',
 '5/26/23, 12:42 AM  ',
 '5/26/23, 12:43 AM  ',
 '5/26/23, 12:43 AM  ',
 '5/26/23, 12:44 AM  ',
 '5/26/23, 12:44 AM  ',
 '5/26/23, 12:45 AM  ',
 '5/26/23, 12:45 AM  ',
 '5/26/23, 12:48 AM  ',
 '5/26/23, 12:49 AM  ',
 '5/26/23, 12:53 AM  ',
 '5/26/23, 12:53 AM  ',
 '5/26/23, 12:54 AM  ',
 '5/26/23, 12:55 AM  ',
 '5/26/23, 12:55 AM  ',
 '5/26/23, 12:55 AM  ',
 '5/26/23, 12:55 AM  ',
 '5/26/23, 12:56 AM  ',
 '5/26/23, 1:07 AM  ',
 '5/26/23, 1:08 AM  ',
 '5/26/23, 11:27 AM  ',
 '5/26/23, 6:35 PM  ',
 '5/26/23, 6:39 PM  ',
 '5/26/23, 6:39 PM  ',
 '5/26/23, 6:52 PM  ',
 '5/26/23, 6:53 PM  ',
 '5/26/23, 6:53 PM  ',
 '5/26/23, 6:53 PM  ',
 '5/26/23, 6:53 PM  ',
 '5/26/23, 6:53 PM  ',
 '5/26/23, 7:20 PM  ',
 '5/26/23, 7:26 PM  ',
 '5/26/23, 7:26 PM  ',
 '5/27/23, 3:15 PM  ',
 '5/27/23, 3:15 PM  ',
 '5/27/23, 3:30 PM  ',
 '5/27/23, 3:32 PM  ',
 '5/27/23, 3:33 PM  ',
 '5/27/23, 10:57 PM  ',
 '5/27/23, 10:57 PM  ',
 '5/27/23, 11:02 PM  ',
 '5/28/23, 12:07 AM  ',
 '5/28/23, 12:09 AM  ',
 '5/28/23, 12:10 AM  ',
 '5/28/23, 12:11 AM  ',
 '5/28/23, 12:13 AM  ',
 '5/28/23, 12:13 AM  ',
 '5/28/23, 12:14 AM  ',
 '5/28/23, 12:16 AM  ',
 '5/28/23, 12:24 AM  ',
 '5/28/23, 12:30 AM  ',
 '5/28/23, 12:48 AM  ',
 '5/28/23, 12:54 AM  ',
 '5/28/23, 1:26 AM  ',
 '5/28/23, 2:27 AM  ',
 '5/28/23, 2:37 AM  ',
 '5/28/23, 2:57 AM  ',
 '5/28/23, 2:58 AM  ',
 '5/28/23, 5:13 AM  ',
 '5/28/23, 7:07 AM  ',
 '5/28/23, 7:07 AM  ',
 '5/28/23, 7:26 AM  ',
 '5/28/23, 7:51 AM  ',
 '5/28/23, 8:00 AM  ',
 '5/28/23, 8:01 AM  ',
 '5/28/23, 8:13 AM  ',
 '5/28/23, 8:20 AM  ',
 '5/28/23, 8:37 AM  ',
 '5/28/23, 8:46 AM  ',
 '5/28/23, 9:23 AM  ',
 '5/28/23, 10:05 AM  ',
 '5/28/23, 10:48 AM  ',
 '5/28/23, 10:50 AM  ',
 '5/28/23, 10:50 AM  ',
 '5/28/23, 10:54 AM  ',
 '5/28/23, 11:29 AM  ',
 '5/28/23, 11:33 AM  ',
 '5/28/23, 11:35 AM  ',
 '5/28/23, 11:39 AM  ',
 '5/28/23, 12:08 PM  ',
 '5/28/23, 12:35 PM  ',
 '5/28/23, 4:46 PM  ',
 '5/29/23, 12:04 AM  ',
 '5/29/23, 12:30 PM  ',
 '5/29/23, 12:33 PM  ',
 '5/29/23, 12:33 PM  ',
 '5/29/23, 1:13 PM  ',
 '5/30/23, 1:39 PM  ',
 '5/31/23, 3:56 PM  ',
 '5/31/23, 4:15 PM  ',
 '5/31/23, 4:19 PM  ',
 '5/31/23, 5:20 PM  ',
 '6/1/23, 8:02 AM  ',
 '6/1/23, 12:07 PM  ',
 '6/1/23, 12:37 PM  ',
 '6/1/23, 4:13 PM  ',
 '6/2/23, 1:28 AM  ',
 '6/2/23, 1:34 AM  ',
 '6/2/23, 2:14 AM  ',
 '6/2/23, 11:09 AM  ',
 '6/2/23, 1:38 PM  ',
 '6/3/23, 2:24 AM  ',
 '6/3/23, 2:24 AM  ',
 '6/3/23, 2:26 AM  ',
 '6/3/23, 2:26 AM  ',
 '6/3/23, 2:26 AM  ',
 '6/3/23, 2:26 AM  ',
 '6/3/23, 2:26 AM  ',
 '6/3/23, 2:26 AM  ',
 '6/3/23, 2:27 AM  ',
 '6/3/23, 2:27 AM  ',
 '6/3/23, 2:27 AM  ',
 '6/3/23, 2:27 AM  ',
 '6/3/23, 2:27 AM  ',
 '6/3/23, 2:28 AM  ',
 '6/3/23, 2:28 AM  ',
 '6/3/23, 2:28 AM  ',
 '6/3/23, 2:28 AM  ',
 '6/3/23, 2:28 AM  ',
 '6/3/23, 2:28 AM  ',
 '6/3/23, 2:28 AM  ',
 '6/3/23, 2:28 AM  ',
 '6/3/23, 2:28 AM  ',
 '6/3/23, 2:29 AM  ',
 '6/3/23, 2:29 AM  ',
 '6/3/23, 2:29 AM  ',
 '6/3/23, 2:29 AM  ',
 '6/3/23, 2:29 AM  ',
 '6/3/23, 2:29 AM  ',
 '6/3/23, 2:30 AM  ',
 '6/3/23, 2:30 AM  ',
 '6/3/23, 2:30 AM  ',
 '6/3/23, 2:30 AM  ',
 '6/3/23, 2:30 AM  ',
 '6/3/23, 2:31 AM  ',
 '6/3/23, 2:31 AM  ',
 '6/3/23, 2:31 AM  ',
 '6/3/23, 2:31 AM  ',
 '6/3/23, 2:31 AM  ',
 '6/3/23, 2:32 AM  ',
 '6/3/23, 2:32 AM  ',
 '6/3/23, 2:32 AM  ',
 '6/3/23, 2:32 AM  ',
 '6/3/23, 2:32 AM  ',
 '6/3/23, 2:32 AM  ',
 '6/3/23, 2:32 AM  ',
 '6/3/23, 2:32 AM  ',
 '6/3/23, 2:33 AM  ',
 '6/3/23, 2:33 AM  ',
 '6/3/23, 2:33 AM  ',
 '6/3/23, 2:33 AM  ',
 '6/3/23, 2:34 AM  ',
 '6/3/23, 2:34 AM  ',
 '6/3/23, 2:34 AM  ',
 '6/3/23, 2:34 AM  ',
 '6/3/23, 2:34 AM  ',
 '6/3/23, 2:34 AM  ',
 '6/3/23, 2:34 AM  ',
 '6/3/23, 2:35 AM  ',
 '6/3/23, 2:35 AM  ',
 '6/3/23, 2:35 AM  ',
 '6/3/23, 2:35 AM  ',
 '6/3/23, 2:35 AM  ',
 '6/3/23, 2:35 AM  ',
 '6/3/23, 2:35 AM  ',
 '6/3/23, 2:36 AM  ',
 '6/3/23, 2:36 AM  ',
 '6/3/23, 2:36 AM  ',
 '6/3/23, 2:36 AM  ',
 '6/3/23, 2:36 AM  ',
 '6/3/23, 2:36 AM  ',
 '6/3/23, 2:37 AM  ',
 '6/3/23, 2:37 AM  ',
 '6/3/23, 2:37 AM  ',
 '6/3/23, 2:37 AM  ',
 '6/3/23, 2:37 AM  ',
 '6/3/23, 2:37 AM  ',
 '6/3/23, 2:37 AM  ',
 '6/3/23, 2:37 AM  ',
 '6/3/23, 2:37 AM  ',
 '6/3/23, 2:37 AM  ',
 '6/3/23, 2:38 AM  ',
 '6/3/23, 2:38 AM  ',
 '6/3/23, 2:38 AM  ',
 '6/3/23, 2:38 AM  ',
 '6/3/23, 2:38 AM  ',
 '6/3/23, 2:38 AM  ',
 '6/3/23, 2:39 AM  ',
 '6/3/23, 2:39 AM  ',
 '6/3/23, 2:39 AM  ',
 '6/3/23, 2:39 AM  ',
 '6/3/23, 2:39 AM  ',
 '6/3/23, 2:39 AM  ',
 '6/3/23, 2:39 AM  ',
 '6/3/23, 2:39 AM  ',
 '6/3/23, 2:39 AM  ',
 '6/3/23, 2:39 AM  ',
 '6/3/23, 2:40 AM  ',
 '6/3/23, 2:40 AM  ',
 '6/3/23, 2:40 AM  ',
 '6/3/23, 2:40 AM  ',
 '6/3/23, 2:40 AM  ',
 '6/3/23, 2:41 AM  ',
 '6/3/23, 2:41 AM  ',
 '6/3/23, 2:41 AM  ',
 '6/3/23, 2:41 AM  ',
 '6/3/23, 2:41 AM  ',
 '6/3/23, 2:41 AM  ',
 '6/3/23, 2:41 AM  ',
 '6/3/23, 2:41 AM  ',
 '6/3/23, 2:42 AM  ',
 '6/3/23, 2:42 AM  ',
 '6/3/23, 2:42 AM  ',
 '6/3/23, 2:42 AM  ',
 '6/3/23, 2:42 AM  ',
 '6/3/23, 2:42 AM  ',
 '6/3/23, 2:42 AM  ',
 '6/3/23, 2:42 AM  ',
 '6/3/23, 2:43 AM  ',
 '6/3/23, 2:43 AM  ',
 '6/3/23, 2:43 AM  ',
 '6/3/23, 2:43 AM  ',
 '6/3/23, 2:43 AM  ',
 '6/3/23, 2:43 AM  ',
 '6/3/23, 2:43 AM  ',
 '6/3/23, 2:43 AM  ',
 '6/3/23, 2:44 AM  ',
 '6/3/23, 2:44 AM  ',
 '6/3/23, 2:44 AM  ',
 '6/3/23, 2:44 AM  ',
 '6/3/23, 2:44 AM  ',
 '6/3/23, 2:44 AM  ',
 '6/3/23, 2:44 AM  ',
 '6/3/23, 2:44 AM  ',
 '6/3/23, 2:45 AM  ',
 '6/3/23, 2:45 AM  ',
 '6/3/23, 2:45 AM  ',
 '6/3/23, 2:45 AM  ',
 '6/3/23, 2:45 AM  ',
 '6/3/23, 2:45 AM  ',
 '6/3/23, 2:46 AM  ',
 '6/3/23, 2:46 AM  ',
 '6/3/23, 2:46 AM  ',
 '6/3/23, 2:46 AM  ',
 '6/3/23, 2:46 AM  ',
 '6/3/23, 2:47 AM  ',
 '6/3/23, 2:47 AM  ',
 '6/3/23, 2:47 AM  ',
 '6/3/23, 2:48 AM  ',
 '6/3/23, 2:48 AM  ',
 '6/3/23, 2:48 AM  ',
 '6/3/23, 2:48 AM  ',
 '6/3/23, 2:48 AM  ',
 '6/3/23, 2:48 AM  ',
 '6/3/23, 2:49 AM  ',
 '6/3/23, 2:49 AM  ',
 '6/3/23, 2:49 AM  ',
 '6/3/23, 2:49 AM  ',
 '6/3/23, 2:49 AM  ',
 '6/3/23, 2:49 AM  ',
 '6/3/23, 2:49 AM  ',
 '6/3/23, 2:50 AM  ',
 '6/3/23, 2:50 AM  ',
 '6/3/23, 2:50 AM  ',
 '6/3/23, 2:50 AM  ',
 '6/3/23, 2:50 AM  ',
 '6/3/23, 2:50 AM  ',
 '6/3/23, 2:50 AM  ',
 '6/3/23, 2:51 AM  ',
 '6/3/23, 2:51 AM  ',
 '6/3/23, 2:51 AM  ',
 '6/3/23, 2:51 AM  ',
 '6/3/23, 2:52 AM  ',
 '6/3/23, 2:52 AM  ',
 '6/3/23, 2:52 AM  ',
 '6/3/23, 2:52 AM  ',
 '6/3/23, 2:52 AM  ',
 '6/3/23, 2:52 AM  ',
 '6/3/23, 2:52 AM  ',
 '6/3/23, 2:53 AM  ',
 '6/3/23, 2:53 AM  ',
 '6/3/23, 2:53 AM  ',
 '6/3/23, 2:53 AM  ',
 '6/3/23, 2:53 AM  ',
 '6/3/23, 2:53 AM  ',
 '6/3/23, 2:53 AM  ',
 '6/3/23, 2:54 AM  ',
 '6/3/23, 2:54 AM  ',
 '6/3/23, 2:54 AM  ',
 '6/3/23, 2:54 AM  ',
 '6/3/23, 2:55 AM  ',
 '6/3/23, 2:55 AM  ',
 '6/3/23, 2:55 AM  ',
 '6/3/23, 2:56 AM  ',
 '6/3/23, 2:56 AM  ',
 '6/3/23, 2:56 AM  ',
 '6/3/23, 2:56 AM  ',
 '6/3/23, 2:57 AM  ',
 '6/3/23, 2:57 AM  ',
 '6/3/23, 2:57 AM  ',
 '6/3/23, 2:58 AM  ',
 '6/3/23, 2:58 AM  ',
 '6/3/23, 2:59 AM  ',
 '6/3/23, 2:59 AM  ',
 '6/3/23, 2:59 AM  ',
 '6/3/23, 2:59 AM  ',
 '6/3/23, 2:59 AM  ',
 '6/3/23, 2:59 AM  ',
 '6/3/23, 3:00 AM  ',
 '6/3/23, 3:00 AM  ',
 '6/3/23, 3:00 AM  ',
 '6/3/23, 3:01 AM  ',
 '6/3/23, 3:01 AM  ',
 '6/3/23, 3:01 AM  ',
 '6/3/23, 3:01 AM  ',
 '6/3/23, 3:01 AM  ',
 '6/3/23, 3:01 AM  ',
 '6/3/23, 3:02 AM  ',
 '6/3/23, 3:02 AM  ',
 '6/3/23, 3:02 AM  ',
 '6/3/23, 3:02 AM  ',
 '6/3/23, 3:03 AM  ',
 '6/3/23, 3:03 AM  ',
 '6/3/23, 3:03 AM  ',
 '6/3/23, 3:04 AM  ',
 '6/3/23, 3:04 AM  ',
 '6/3/23, 3:04 AM  ',
 '6/3/23, 3:04 AM  ',
 '6/3/23, 3:04 AM  ',
 '6/3/23, 3:05 AM  ',
 '6/3/23, 3:05 AM  ',
 '6/3/23, 3:05 AM  ',
 '6/3/23, 3:05 AM  ',
 '6/3/23, 3:05 AM  ',
 '6/3/23, 3:05 AM  ',
 '6/3/23, 3:05 AM  ',
 '6/3/23, 3:05 AM  ',
 '6/3/23, 3:05 AM  ',
 '6/3/23, 3:05 AM  ',
 '6/3/23, 3:05 AM  ',
 '6/3/23, 3:05 AM  ',
 '6/3/23, 3:05 AM  ',
 '6/3/23, 3:05 AM  ',
 '6/3/23, 3:05 AM  ',
 '6/3/23, 3:06 AM  ',
 '6/3/23, 3:06 AM  ',
 '6/3/23, 3:06 AM  ',
 '6/3/23, 3:06 AM  ',
 '6/3/23, 3:06 AM  ',
 '6/3/23, 3:07 AM  ',
 '6/3/23, 3:07 AM  ',
 '6/3/23, 3:07 AM  ',
 '6/3/23, 3:07 AM  ',
 '6/3/23, 3:07 AM  ',
 '6/3/23, 3:07 AM  ',
 '6/3/23, 3:08 AM  ',
 '6/3/23, 3:08 AM  ',
 '6/3/23, 3:08 AM  ',
 '6/3/23, 3:08 AM  ',
 '6/3/23, 3:08 AM  ',
 '6/3/23, 3:08 AM  ',
 '6/3/23, 3:08 AM  ',
 '6/3/23, 3:08 AM  ',
 '6/3/23, 3:08 AM  ',
 '6/3/23, 3:09 AM  ',
 '6/3/23, 3:09 AM  ',
 '6/3/23, 3:09 AM  ',
 '6/3/23, 3:09 AM  ',
 '6/3/23, 3:09 AM  ',
 '6/3/23, 3:09 AM  ',
 '6/3/23, 3:09 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:10 AM  ',
 '6/3/23, 3:11 AM  ',
 '6/3/23, 3:11 AM  ',
 '6/3/23, 3:11 AM  ',
 '6/3/23, 3:11 AM  ',
 '6/3/23, 3:11 AM  ',
 '6/3/23, 3:11 AM  ',
 '6/3/23, 3:11 AM  ',
 '6/3/23, 3:11 AM  ',
 '6/3/23, 3:11 AM  ',
 '6/3/23, 3:11 AM  ',
 '6/3/23, 3:11 AM  ',
 '6/3/23, 3:11 AM  ',
 '6/3/23, 3:11 AM  ',
 '6/3/23, 3:11 AM  ',
 '6/3/23, 3:11 AM  ',
 '6/3/23, 3:11 AM  ',
 '6/3/23, 3:11 AM  ',
 '6/3/23, 3:11 AM  ',
 '6/3/23, 3:12 AM  ',
 '6/3/23, 3:12 AM  ',
 '6/3/23, 3:12 AM  ',
 '6/3/23, 3:12 AM  ',
 '6/3/23, 3:12 AM  ',
 '6/3/23, 3:12 AM  ',
 '6/3/23, 3:12 AM  ',
 '6/3/23, 3:12 AM  ',
 '6/3/23, 3:12 AM  ',
 '6/3/23, 3:12 AM  ',
 '6/3/23, 3:12 AM  ',
 '6/3/23, 3:12 AM  ',
 '6/3/23, 3:12 AM  ',
 '6/3/23, 3:12 AM  ',
 '6/3/23, 3:12 AM  ',
 '6/3/23, 3:12 AM  ',
 '6/3/23, 3:12 AM  ',
 '6/3/23, 3:13 AM  ',
 '6/3/23, 3:13 AM  ',
 '6/3/23, 3:13 AM  ',
 '6/3/23, 3:13 AM  ',
 '6/3/23, 3:13 AM  ',
 '6/3/23, 3:13 AM  ',
 '6/3/23, 3:13 AM  ',
 '6/3/23, 3:14 AM  ',
 '6/3/23, 3:14 AM  ',
 '6/3/23, 3:14 AM  ',
 '6/3/23, 3:14 AM  ',
 '6/3/23, 3:14 AM  ',
 '6/3/23, 3:14 AM  ',
 '6/3/23, 3:14 AM  ',
 '6/3/23, 3:14 AM  ',
 '6/3/23, 3:15 AM  ',
 '6/3/23, 3:15 AM  ',
 '6/3/23, 3:15 AM  ',
 '6/3/23, 3:15 AM  ',
 '6/3/23, 3:15 AM  ',
 '6/3/23, 3:15 AM  ',
 '6/3/23, 3:15 AM  ',
 '6/3/23, 3:16 AM  ',
 '6/3/23, 3:16 AM  ',
 '6/3/23, 3:16 AM  ',
 '6/3/23, 3:16 AM  ',
 '6/3/23, 3:16 AM  ',
 '6/3/23, 3:16 AM  ',
 '6/3/23, 3:16 AM  ',
 '6/3/23, 3:17 AM  ',
 '6/3/23, 3:17 AM  ',
 '6/3/23, 3:17 AM  ',
 '6/3/23, 3:17 AM  ',
 '6/3/23, 3:17 AM  ',
 '6/3/23, 3:17 AM  ',
 '6/3/23, 3:17 AM  ',
 '6/3/23, 3:18 AM  ',
 '6/3/23, 3:18 AM  ',
 '6/3/23, 3:18 AM  ',
 '6/3/23, 3:18 AM  ',
 '6/3/23, 3:18 AM  ',
 '6/3/23, 3:18 AM  ',
 '6/3/23, 3:19 AM  ',
 '6/3/23, 3:19 AM  ',
 '6/3/23, 3:19 AM  ',
 '6/3/23, 3:19 AM  ',
 '6/3/23, 3:19 AM  ',
 '6/3/23, 3:19 AM  ',
 '6/3/23, 3:19 AM  ',
 '6/3/23, 3:20 AM  ',
 '6/3/23, 3:20 AM  ',
 '6/3/23, 3:20 AM  ',
 '6/3/23, 3:20 AM  ',
 '6/3/23, 3:20 AM  ',
 '6/3/23, 3:20 AM  ',
 '6/3/23, 3:20 AM  ',
 '6/3/23, 3:21 AM  ',
 '6/3/23, 3:21 AM  ',
 '6/3/23, 3:21 AM  ',
 '6/3/23, 3:21 AM  ',
 '6/3/23, 3:21 AM  ',
 '6/3/23, 3:21 AM  ',
 '6/3/23, 3:21 AM  ',
 '6/3/23, 3:21 AM  ',
 '6/3/23, 3:21 AM  ',
 '6/3/23, 3:21 AM  ',
 '6/3/23, 3:21 AM  ',
 '6/3/23, 3:22 AM  ',
 '6/3/23, 3:22 AM  ',
 '6/3/23, 3:22 AM  ',
 '6/3/23, 3:22 AM  ',
 '6/3/23, 3:22 AM  ',
 '6/3/23, 3:22 AM  ',
 '6/3/23, 3:22 AM  ',
 '6/3/23, 3:22 AM  ',
 '6/3/23, 3:22 AM  ',
 '6/3/23, 3:23 AM  ',
 '6/3/23, 3:23 AM  ',
 '6/3/23, 3:23 AM  ',
 '6/3/23, 3:23 AM  ',
 '6/3/23, 3:23 AM  ',
 '6/3/23, 3:23 AM  ',
 '6/3/23, 3:23 AM  ',
 '6/3/23, 3:23 AM  ',
 '6/3/23, 3:24 AM  ',
 '6/3/23, 3:24 AM  ',
 '6/3/23, 3:24 AM  ',
 '6/3/23, 3:24 AM  ',
 '6/3/23, 3:24 AM  ',
 '6/3/23, 3:24 AM  ',
 '6/3/23, 3:24 AM  ',
 '6/3/23, 3:24 AM  ',
 '6/3/23, 3:24 AM  ',
 '6/3/23, 3:25 AM  ',
 '6/3/23, 3:25 AM  ',
 '6/3/23, 3:25 AM  ',
 '6/3/23, 3:25 AM  ',
 '6/3/23, 3:25 AM  ',
 '6/3/23, 3:25 AM  ',
 '6/3/23, 3:25 AM  ',
 '6/3/23, 3:26 AM  ',
 '6/3/23, 3:26 AM  ',
 '6/3/23, 3:26 AM  ',
 '6/3/23, 3:26 AM  ',
 '6/3/23, 3:26 AM  ',
 '6/3/23, 3:26 AM  ',
 '6/3/23, 3:26 AM  ',
 '6/3/23, 3:26 AM  ',
 '6/3/23, 3:26 AM  ',
 '6/3/23, 3:27 AM  ',
 '6/3/23, 3:27 AM  ',
 '6/3/23, 3:27 AM  ',
 '6/3/23, 3:27 AM  ',
 '6/3/23, 3:27 AM  ',
 '6/3/23, 3:27 AM  ',
 '6/3/23, 3:27 AM  ',
 '6/3/23, 3:27 AM  ',
 '6/3/23, 3:27 AM  ',
 '6/3/23, 3:28 AM  ',
 '6/3/23, 3:28 AM  ',
 '6/3/23, 3:28 AM  ',
 '6/3/23, 3:28 AM  ',
 '6/3/23, 3:28 AM  ',
 '6/3/23, 3:28 AM  ',
 '6/3/23, 3:28 AM  ',
 '6/3/23, 3:28 AM  ',
 '6/3/23, 3:28 AM  ',
 '6/3/23, 3:28 AM  ',
 '6/3/23, 3:28 AM  ',
 '6/3/23, 3:29 AM  ',
 '6/3/23, 3:29 AM  ',
 '6/3/23, 3:29 AM  ',
 '6/3/23, 3:29 AM  ',
 '6/3/23, 3:29 AM  ',
 '6/3/23, 3:29 AM  ',
 '6/3/23, 3:29 AM  ',
 '6/3/23, 3:30 AM  ',
 '6/3/23, 3:30 AM  ',
 '6/3/23, 3:30 AM  ',
 '6/3/23, 3:30 AM  ',
 '6/3/23, 3:30 AM  ',
 '6/3/23, 3:30 AM  ',
 '6/3/23, 3:30 AM  ',
 '6/3/23, 3:30 AM  ',
 '6/3/23, 3:30 AM  ',
 '6/3/23, 3:30 AM  ',
 '6/3/23, 3:31 AM  ',
 '6/3/23, 3:31 AM  ',
 '6/3/23, 3:31 AM  ',
 '6/3/23, 3:31 AM  ',
 '6/3/23, 3:31 AM  ',
 '6/3/23, 3:31 AM  ',
 '6/3/23, 3:31 AM  ',
 '6/3/23, 3:32 AM  ',
 '6/3/23, 3:32 AM  ',
 '6/3/23, 3:32 AM  ',
 '6/3/23, 3:32 AM  ',
 '6/3/23, 3:32 AM  ',
 '6/3/23, 3:32 AM  ',
 '6/3/23, 3:32 AM  ',
 '6/3/23, 3:32 AM  ',
 '6/3/23, 3:32 AM  ',
 '6/3/23, 3:32 AM  ',
 '6/3/23, 3:32 AM  ',
 '6/3/23, 3:33 AM  ',
 '6/3/23, 3:33 AM  ',
 '6/3/23, 3:33 AM  ',
 '6/3/23, 3:33 AM  ',
 '6/3/23, 3:34 AM  ',
 '6/3/23, 3:34 AM  ',
 '6/3/23, 3:34 AM  ',
 '6/3/23, 3:34 AM  ',
 '6/3/23, 3:34 AM  ',
 '6/3/23, 3:34 AM  ',
 '6/3/23, 3:35 AM  ',
 '6/3/23, 3:35 AM  ',
 '6/3/23, 3:35 AM  ',
 '6/3/23, 3:36 AM  ',
 '6/3/23, 3:36 AM  ',
 '6/3/23, 3:36 AM  ',
 '6/3/23, 3:36 AM  ',
 '6/3/23, 3:36 AM  ',
 '6/3/23, 3:36 AM  ',
 '6/3/23, 3:37 AM  ',
 '6/3/23, 3:37 AM  ',
 '6/3/23, 3:37 AM  ',
 '6/3/23, 3:37 AM  ',
 '6/3/23, 3:37 AM  ',
 '6/3/23, 3:37 AM  ',
 '6/3/23, 3:37 AM  ',
 '6/3/23, 3:37 AM  ',
 '6/3/23, 3:38 AM  ',
 '6/3/23, 3:38 AM  ',
 '6/3/23, 3:38 AM  ',
 '6/3/23, 3:38 AM  ',
 '6/3/23, 3:38 AM  ',
 '6/3/23, 3:38 AM  ',
 '6/3/23, 3:38 AM  ',
 '6/3/23, 3:39 AM  ',
 '6/3/23, 3:39 AM  ',
 '6/3/23, 3:39 AM  ',
 '6/3/23, 3:39 AM  ',
 '6/3/23, 3:40 AM  ',
 '6/3/23, 3:40 AM  ',
 '6/3/23, 3:41 AM  ',
 '6/3/23, 3:41 AM  ',
 '6/3/23, 3:41 AM  ',
 '6/3/23, 3:41 AM  ',
 '6/3/23, 3:42 AM  ',
 '6/3/23, 3:42 AM  ',
 '6/3/23, 3:42 AM  ',
 '6/3/23, 3:42 AM  ',
 '6/3/23, 3:43 AM  ',
 '6/3/23, 3:43 AM  ',
 '6/3/23, 3:43 AM  ',
 '6/3/23, 3:44 AM  ',
 '6/3/23, 3:44 AM  ',
 '6/3/23, 3:45 AM  ',
 '6/3/23, 3:45 AM  ',
 '6/3/23, 3:45 AM  ',
 '6/3/23, 3:45 AM  ',
 '6/3/23, 3:46 AM  ',
 '6/3/23, 3:46 AM  ',
 '6/3/23, 3:46 AM  ',
 '6/3/23, 3:46 AM  ',
 '6/3/23, 3:46 AM  ',
 '6/3/23, 3:46 AM  ',
 '6/3/23, 3:46 AM  ',
 '6/3/23, 3:46 AM  ',
 '6/3/23, 3:46 AM  ',
 '6/3/23, 3:47 AM  ',
 '6/3/23, 3:47 AM  ',
 '6/3/23, 3:47 AM  ',
 '6/3/23, 3:47 AM  ',
 '6/3/23, 3:47 AM  ',
 '6/3/23, 3:47 AM  ',
 '6/3/23, 3:47 AM  ',
 '6/3/23, 3:47 AM  ',
 '6/3/23, 3:48 AM  ',
 '6/3/23, 3:48 AM  ',
 '6/3/23, 3:48 AM  ',
 '6/3/23, 3:48 AM  ',
 '6/3/23, 3:48 AM  ',
 '6/3/23, 3:48 AM  ',
 '6/3/23, 3:49 AM  ',
 '6/3/23, 3:49 AM  ',
 '6/3/23, 3:49 AM  ',
 '6/3/23, 3:49 AM  ',
 '6/3/23, 3:49 AM  ',
 '6/3/23, 3:49 AM  ',
 '6/3/23, 3:49 AM  ',
 '6/3/23, 3:49 AM  ',
 '6/3/23, 3:49 AM  ',
 '6/3/23, 3:50 AM  ',
 '6/3/23, 3:50 AM  ',
 '6/3/23, 3:50 AM  ',
 '6/3/23, 3:50 AM  ',
 '6/3/23, 3:50 AM  ',
 '6/3/23, 3:50 AM  ',
 '6/3/23, 3:50 AM  ',
 '6/3/23, 3:51 AM  ',
 '6/3/23, 3:51 AM  ',
 '6/3/23, 3:51 AM  ',
 '6/3/23, 3:51 AM  ',
 '6/3/23, 3:51 AM  ',
 '6/3/23, 3:51 AM  ',
 '6/3/23, 3:51 AM  ',
 '6/3/23, 3:51 AM  ',
 '6/3/23, 3:52 AM  ',
 '6/3/23, 3:52 AM  ',
 '6/3/23, 3:52 AM  ',
 '6/3/23, 3:52 AM  ',
 '6/3/23, 3:52 AM  ',
 '6/3/23, 3:53 AM  ',
 '6/3/23, 3:53 AM  ',
 '6/3/23, 3:53 AM  ',
 '6/3/23, 3:53 AM  ',
 '6/3/23, 3:54 AM  ',
 '6/3/23, 3:54 AM  ',
 '6/3/23, 3:54 AM  ',
 '6/3/23, 3:54 AM  ',
 '6/3/23, 3:54 AM  ',
 '6/3/23, 3:55 AM  ',
 '6/3/23, 3:55 AM  ',
 '6/3/23, 3:55 AM  ',
 '6/3/23, 3:55 AM  ',
 '6/3/23, 3:55 AM  ',
 '6/3/23, 3:55 AM  ',
 '6/3/23, 3:55 AM  ',
 '6/3/23, 3:55 AM  ',
 '6/3/23, 3:55 AM  ',
 '6/3/23, 3:56 AM  ',
 '6/3/23, 3:56 AM  ',
 '6/3/23, 3:56 AM  ',
 '6/3/23, 3:56 AM  ',
 '6/3/23, 3:56 AM  ',
 '6/3/23, 3:56 AM  ',
 '6/3/23, 3:57 AM  ',
 '6/3/23, 3:57 AM  ',
 '6/3/23, 3:57 AM  ',
 '6/3/23, 3:58 AM  ',
 '6/3/23, 3:58 AM  ',
 '6/3/23, 3:58 AM  ',
 '6/3/23, 3:58 AM  ',
 '6/3/23, 3:59 AM  ',
 '6/3/23, 3:59 AM  ',
 '6/3/23, 4:00 AM  ',
 '6/3/23, 4:00 AM  ',
 '6/3/23, 4:00 AM  ',
 '6/3/23, 4:01 AM  ',
 '6/3/23, 4:01 AM  ',
 '6/3/23, 4:03 AM  ',
 '6/3/23, 11:24 AM  ',
 '6/3/23, 11:28 AM  ',
 '6/3/23, 8:21 PM  ',
 '6/3/23, 8:31 PM  ',
 '6/3/23, 8:31 PM  ',
 '6/3/23, 8:32 PM  ',
 '6/3/23, 8:32 PM  ',
 '6/3/23, 8:39 PM  ',
 '6/3/23, 8:39 PM  ',
 '6/3/23, 8:39 PM  ',
 '6/3/23, 8:41 PM  ',
 '6/3/23, 8:42 PM  ',
 '6/3/23, 8:43 PM  ',
 '6/3/23, 8:43 PM  ',
 '6/3/23, 8:44 PM  ',
 '6/3/23, 8:44 PM  ',
 '6/3/23, 8:45 PM  ',
 '6/3/23, 8:45 PM  ',
 '6/3/23, 8:45 PM  ',
 '6/3/23, 8:47 PM  ',
 '6/3/23, 8:48 PM  ',
 '6/3/23, 8:49 PM  ',
 '6/3/23, 8:50 PM  ',
 '6/3/23, 9:53 PM  ',
 '6/3/23, 9:54 PM  ',
 '6/3/23, 10:06 PM  ',
 '6/3/23, 10:12 PM  ',
 '6/3/23, 10:12 PM  ',
 '6/3/23, 10:12 PM  ',
 '6/4/23, 12:33 AM  ',
 '6/5/23, 3:09 AM  ',
 '6/5/23, 3:11 AM  ',
 '6/5/23, 2:39 PM  ',
 '6/5/23, 3:14 PM  ',
 '6/5/23, 11:15 PM  ',
 '6/5/23, 11:15 PM  ',
 '6/5/23, 11:15 PM  ',
 '6/6/23, 10:11 AM  ',
 '6/7/23, 2:28 PM  ',
 '6/7/23, 2:28 PM  ',

In [145]:
df = pd.DataFrame({"user_message": message,"date":dates})

# convert message_date type
df['date'] = pd.to_datetime(df['date'].str.strip() ,format = '%m/%d/%y, %I:%M %p')
df.head()

                                        user_message                date
0  Messages and calls are end-to-end encrypted. N... 2023-05-22 01:52:00
1         +91 77248 81647: Happy birthday Nisha 🥳🎉\n 2023-05-22 01:55:00
2    +91 77248 81647: Happy birthday prithviraj 🎉🥳\n 2023-05-22 01:56:00
3  +91 89899 71799: Happiest Birthday to you both... 2023-05-22 02:38:00
4  Bhumika IT: Happy birthday Nisha and prithviraj\n 2023-05-22 05:29:00

In [146]:
# separate user and message 
users = []
messages =[]
for message in df['user_message']:
    entry = re.split('([\w\W]+?):\s',message)
    if entry [1:]: # user message
        users.append(entry[1])
        messages.append(entry[2])
    else:
        users.append('group_notification')
        messages.append(entry[0]) 
        
df['user'] =users
df['messages'] =messages
df.drop(columns=['user_message'],inplace=True) 

df.sample(10)

,date,user,messages
5988,2023-11-02 20:30:00,+91 93431 43604,Aree bhai dil se bura laga💔\n
4468,2023-10-13 17:23:00,+91 75093 83109,<Media omitted>\n
15933,2025-02-19 23:29:00,Arth,Mere paas toh voh bhi nhi hai\n
2337,2023-09-14 23:19:00,Bhumika IT,sheraj\n
1101,2023-06-14 00:36:00,Yuvi,Happy birthday @918435699761 💥💥🎉\n
9245,2024-02-04 14:08:00,Himanshu IT,Happy birthday @919589786499 🥳🥳\n
16065,2025-02-20 01:03:00,Edward,Too jab bange budget tab chl dnege😎\n
9624,2024-02-20 21:47:00,Siddhu Moose Wala,Abbe 😂 Kohli ka beta hua hai Mera nhi\n
4174,2023-10-05 21:55:00,+91 93431 43604,😂😂bhej tu to \nDikkat ki chinta na kr\n
15331,2024-12-17 12:54:00,+91 62688 18798,Happy birthday @918770063064 🎉🥳 bhai\n

In [148]:
df['Day'] = df['date'].dt.day_name()
df['Month'] = df['date'].dt.month_name()

df['Year'] = df['date'].dt.year
df.drop(columns=['date'],inplace=True)

In [149]:
df.head()

,user,messages,Day,Month,Year
0,group_notification,Messages and calls are end-to-end encrypted. N...,Monday,May,2023
1,+91 77248 81647,Happy birthday Nisha 🥳🎉\n,Monday,May,2023
2,+91 77248 81647,Happy birthday prithviraj 🎉🥳\n,Monday,May,2023
3,+91 89899 71799,Happiest Birthday to you both 🎉🎉 @919669101981...,Monday,May,2023
4,Bhumika IT,Happy birthday Nisha and prithviraj\n,Monday,May,2023